all:
				mkdir -p data
				mkdir -p data/user
				mkdir -p data/user/train
				mkdir -p data/user/friend
				mkdir -p data/user/test
				mkdir -p data/user/id
				mkdir -p data/checkin
				mkdir -p data/checkin/train
				mkdir -p data/checkin/train/train
				mkdir -p data/checkin/train/test
				mkdir -p data/checkin/test
				mkdir -p data/checkin/cities
				mkdir -p data/checkin/cities/train
				mkdir -p data/checkin/cities/test
				mkdir -p data/neighbor
				mkdir -p data/poi_full
				mkdir -p data/poi
				mkdir -p data/poi/id
				mkdir -p data/result
				mkdir -p data/result/reclist
				mkdir -p data/result/util
				mkdir -p data/result/img
				mkdir -p data/result/metrics
				mkdir -p data/id
