all:
	mkdir -p data/results
	mkdir -p data/results/util
	mkdir -p data/results/img
	mkdir -p data/results/reclist
	mkdir -p data/results/metrics
	mkdir -p data/datasets
	mkdir -p data/datasets/poi
	mkdir -p data/datasets/poi/id
	mkdir -p data/datasets/poi_full
	mkdir -p data/datasets/user
	mkdir -p data/datasets/user/friend
	mkdir -p data/datasets/user/id
	mkdir -p data/datasets/user/.ipynb_checkpoints
	mkdir -p data/datasets/checkin
	mkdir -p data/datasets/checkin/train
	mkdir -p data/datasets/checkin/test
	mkdir -p data/datasets/neighbor
	mkdir -p data/datasets/neighbor/.ipynb_checkpoints
