
# #+ATTR_HTML: :style margin-left: auto; margin-right: auto;
# https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Sanzio_01_Pythagoras.jpg/800px-Sanzio_01_Pythagoras.jpg]]

* Buscas


Anos para busca: 2017,2018,2019

Conferências para busca: RecSys, SIGIR, ICKM, WSDM, WWW

** 2019

*** ACM
não ocorreu até então. <2019-07-23 Tue>

artigos que podem ser interessantes pelo título:

Short papers:

- User-Centered Evaluation of Strategies for Recommending Sequences of Points of Interest to Groups

Long papers:

empty

*** WWW

- R2SIGTP: a Novel Real-Time Recommendation System with Integration of Geography and Temporal Preference for Next Point-of-Interest


*** Outros


** 2018
*** ACM
artigos que podem ser interessantes pelo título:

Short papers:

- CLoSe: Contextualized Location Sequence Recommender
- Harnessing A Generalised User Behaviour Model for Next-POI Recommendation

Long papers:

empty




** 2017
*** ACM
artigos que podem ser interessantes pelo título:

Short papers:

- Geographical Diversification in POI Recommendation: Toward Improved Coverage on Interested Areas 

Long papers:

empty








* Artigo "An Experimental Evaluation of Point-of-interest Recommendation in Location-based Social Networks"
Nome de cada artigo para cada modelo:

- Exploring temporal effects for location recommendation on location-based social networks
- Exploiting geographical neighborhood characteristics for location recommendation
- GeoMF: joint geographical modeling and matrix factorization for point-of-interest recommendation
- Rank-geofm: A ranking based geographical factorization method for point of interest recommendation
- Point-of-interest recommendations: Learning potential check-ins from friends
- Fused matrix factorization with geographical and social influence in location-based social networks
- A general geographical probabilistic factor model for point of interest recommendation
- Location recommendation in location-based social networks using user check-in data
- Exploiting geographical influence for collaborative point-of-interest recommendation
- igslr: personalized geo-social location recommendation: a kernel density estimation approach
- Lore: Exploiting sequential influence for location recommendations
- Geosoca: Exploiting geographical, social and categorical correlations for point-of-interest recommendations


Modelos:

- MF Models
- LRT
- IRenMF
- GeoMF
- RankGeoFM
- ASMF


- Poisson Factor Models
- MGMPFM
- GeoPFM


- Link-based Models
- LFBCA


- Hybrid Models
- USG
- iGSLR
- LORE
- GeoSoCa

** Matrix factorization models
*** LRT
É um modelo de MF time-enhanced. Baseado no fato de que o comportamento do usuario muda com o tempo. Cada usuario tem fatores latentes diferentes para cada intervalo de tempo. A recomendação é feita com base em todos fatores latentes.

/Temporal-influence/

Para modelar as preferencias dos usuarios para diferentes intervalos de tempos o modelo LRT fatora a matriz de check-in $C^(t)$ para cada intervalo de tempo $t$ separadamente, tal que $t \in \{0,1,\dots,23\}$ é uma hora em um dia. Para a função objetivo um termo regularizador é adicionado pela intuição de que usuarios interesados em intervalos de tempos iguais são iguais. O termo é formalizado como: 





* Não utilizado
  Não deu bons resultados, logo foi utilizado outro método para busca pelos principais artigos.
** Selecionando e filtrando os artigos pelo título
 Aqui irá ser feito uma filtragem de todos artigos para os que pelo título parecem serem melhores de analisados. Depois títulos erroneamente filtrados podem voltar para a base.

 ✓ Aprovado

 ✗ Recusado

 ? Não decidido

*** Matrix factorization

 1. GeoMF: joint geographical modeling and matrix factorization for point-of-interest recommendation ✓
 2. Content-aware point of interest recommendation on location-based social networks ✗
 3. Fused matrix factorization with geographical and social influence in location-based social networks ✓
 4. Rank-geofm: A ranking based geographical factorization method for point of interest recommendation ✓
 5. Learning geographical preferences for point-of-interest recommendation ? PMF, não sei se entra ainda, 2013
 6. POI recommendation: towards fused matrix factorization with geographical and temporal influences ? 2015 GeoMF-TD, sem conteudo pdf
 7. Matrix factorization techniques for context aware recommendation ✗
 8. A survey of point-of-interest recommendation in location-based social networks ✗
 9. Context-aware probabilistic matrix factorization modeling for point-of-interest recommendation ✗
 10. Context-aware point-of-interest recommendation using tensor factorization with social regularization ✓ / Context-aware point of interest recommendation using tensor factorization ?
 11. What your images reveal: Exploiting visual contents for point-of-interest recommendation ✗
 12. STELLAR: spatial-temporal latent ranking for successive point-of-interest recommendation ✗
 13. Context-aware points of interest suggestion with dynamic weather data management ✗
 14. Unified point-of-interest recommendation with temporal interval assessment ?
 15. Schedule a rich sentimental travel via sentimental POI mining and recommendation
 16. Bridging collaborative filtering and semi-supervised learning: a neural approach for poi recommendation
 17. POI recommendation through cross-region collaborative filtering
 18. A temporal-aware POI recommendation system using context-aware tensor decomposition and weighted HITS
 19. Learning graph-based poi embedding for location-based recommendation
 20. Partition-based collaborative tensor factorization for POI recommendation
 21. Collaborative filtering meets mobile recommendation: A user-centered approach
 22. Personalized point-of-interest recommendation by mining users' preference transition
 23. Point-of-interest recommendation in location based social networks with topic and location awareness
 24. Where you like to go next: Successive point-of-interest recommendation
 25. STS: A Context-Aware Mobile Recommender System for Places of Interest.
 26. Geotecs: exploiting geographical, temporal, categorical and social aspects for personalized poi recommendation
 27. Point-of-interest recommender systems: A separate-space perspective
 28. Joint modeling of users' interests and mobility patterns for point-of-interest recommendation
 29. Inferring a personalized next point-of-interest recommendation model with latent behavior patterns
 30. Social topic modeling for point-of-interest recommendation in location-based social networks

** Busca no google scholar
   Aqui só é feito a busca no scholar e os resultados são botados ai.

   Primeiro é feito a query, o resultado da query é botado como uma lista.


*** Matrix factorization
 Query: recommender system poi matrix factorization

 #+NAME: mfarticles
 1. GeoMF: joint geographical modeling and matrix factorization for point-of-interest recommendation
 2. Content-aware point of interest recommendation on location-based social networks
 3. Fused matrix factorization with geographical and social influence in location-based social networks
 4. Rank-geofm: A ranking based geographical factorization method for point of interest recommendation
 5. Learning geographical preferences for point-of-interest recommendation
 6. POI recommendation: towards fused matrix factorization with geographical and temporal influences
 7. Matrix factorization techniques for context aware recommendation
 8. A survey of point-of-interest recommendation in location-based social networks
 9. Context-aware probabilistic matrix factorization modeling for point-of-interest recommendation
 10. Context-aware point-of-interest recommendation using tensor factorization with social regularization
 11. What your images reveal: Exploiting visual contents for point-of-interest recommendation
 12. STELLAR: spatial-temporal latent ranking for successive point-of-interest recommendation
 13. Context-aware points of interest suggestion with dynamic weather data management
 14. Unified point-of-interest recommendation with temporal interval assessment
 15. Schedule a rich sentimental travel via sentimental POI mining and recommendation
 16. Bridging collaborative filtering and semi-supervised learning: a neural approach for poi recommendation
 17. POI recommendation through cross-region collaborative filtering
 18. A temporal-aware POI recommendation system using context-aware tensor decomposition and weighted HITS
 19. Learning graph-based poi embedding for location-based recommendation
 20. Partition-based collaborative tensor factorization for POI recommendation
 21. Collaborative filtering meets mobile recommendation: A user-centered approach
 22. Personalized point-of-interest recommendation by mining users' preference transition
 23. Point-of-interest recommendation in location based social networks with topic and location awareness
 24. Where you like to go next: Successive point-of-interest recommendation
 25. STS: A Context-Aware Mobile Recommender System for Places of Interest.
 26. Geotecs: exploiting geographical, temporal, categorical and social aspects for personalized poi recommendation
 27. Point-of-interest recommender systems: A separate-space perspective
 28. Joint modeling of users' interests and mobility patterns for point-of-interest recommendation
 29. Inferring a personalized next point-of-interest recommendation model with latent behavior patterns
 30. Social topic modeling for point-of-interest recommendation in location-based social networks

 #+BEGIN_SRC emacs-lisp :var list=mfarticles
					   ;(mapcar 'insert list)
   (while (not (null list))
     (doi-utils-add-entry-from-crossref-query (car (car list)) "./doc.bib")
     (setq list (cdr list)))
 #+END_SRC

 #+RESULTS:

*** Content-based filtering
 Query: recommender system poi content-based filtering

 1. Author topic model-based collaborative filtering for personalized POI recommendations
 2. A hybrid recommender system for context-aware recommendations of mobile applications
 3. Using location for personalized POI recommendations in mobile environments
 4. Mobile recommender systems in tourism
 5. Exploiting geographical influence for collaborative point-of-interest recommendation
 6. A web-based pervasive recommendation system for mobile tourist guides
 7. Dynamic particle swarm optimization for personalized recommender system based on electroencephalography feedback.
 8. A hybrid context aware system for tourist guidance based on collaborative filtering
 9. Personalization method for tourist point of interest (POI) recommendation
 10. [PDF] Context and intention-awareness in pois recommender systems

 Query: recommender system poi content-based

 1. A web-based pervasive recommendation system for mobile tourist guides
 2. Mobile recommender systems in tourism
 3. A hybrid recommender system for context-aware recommendations of mobile applications
 4. Using location for personalized POI recommendations in mobile environments
 5. Author topic model-based collaborative filtering for personalized POI recommendations
 6. Location-adapted music recommendation using tags
 7. A mobile tourism recommender system
 8. Dynamic particle swarm optimization for personalized recommender system based on electroencephalography feedback.
 9. Exploiting geographical influence for collaborative point-of-interest recommendation
 10. A context-aware mobile recommender system based on location and trajectory

*** Collaborative filtering

 Query: recommender system poi collaborative filtering

 1. Exploiting geographical influence for collaborative point-of-interest recommendation
 2. Using location for personalized POI recommendations in mobile environments
 3. Author topic model-based collaborative filtering for personalized POI recommendations
 4. Bridging collaborative filtering and semi-supervised learning: a neural approach for poi recommendation
 5. Mobile recommender systems in tourism
 6. A hybrid recommender system for context-aware recommendations of mobile applications
 7. POI recommendation through cross-region collaborative filtering
 8. Using context-aware collaborative filtering for POI recommendations in mobile guides
 9. A hybrid context aware system for tourist guidance based on collaborative filtering
 10. Location-based recommendation system
 11. A web-based pervasive recommendation system for mobile tourist guides
 12. Content-aware point of interest recommendation on location-based social networks
 13. A mobile tourism recommender system
 14. Personalization method for tourist point of interest (POI) recommendation
 15. [PDF] Using trajectories for collaborative filtering-based POI recommendation.
 16. Collaborative location and activity recommendations with GPS history data
 17. A mobile 3D-GIS hybrid recommender system for tourism
 18. Context-aware intelligent recommendation system for tourism
 19. Travel recommendation via author topic model based collaborative filtering
 20. Collaborative filtering meets mobile recommendation: A user-centered approach

*** Link-Based

 Query: recommender system poi link-based link based

 1. Maps: A multi aspect personalized poi recommender system
 2. An experimental evaluation of point-of-interest recommendation in location-based social networks
 3. Knowledge-based identification of music suited for places of interest
 4. Location-recommendation-aware virtual network embedding in energy-efficient optical-wireless hybrid networks supporting 5G models
 5. Swarm intelligence clustering ensemble based point of interest recommendation for social cyber-physical systems
 6. Privacy aspects of recommender systems
 7. A hybrid quantum-induced swarm intelligence clustering for the urban trip recommendation in smart city
 8. A weighted multi-attribute method for matching user-generated points of interest
 9. Context-aware and multilingual information extraction for a tourist recommender system
 10. Recommender systems: Models and techniques

* End
End
